version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/gateway/postgres/migrations:/migrations

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775"   # UDP port for the agent
      - "6831:6831/udp"  # UDP port for the agent
      - "6832:6832/udp"  # Another UDP port for the agent
      - "5778:5778"   # HTTP port for the agent
      - "16686:16686" # Port for Jaeger UI
      - "14250:14250" # Port for GRPC
      - "14267:14267" # Port for Collector
      - "14268:14268" # Port for Collector
      - "4317:4317"   # OTLP gRPC endpoint
      - "4318:4318"   # OTLP HTTP endpoint
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411  # Expose Zipkin API for compatibility
    networks:
      - jaeger-network

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    depends_on:
      - jaeger
    networks:
      - monitoring
      - jaeger-network
    volumes:
      - grafana-data:/var/lib/grafana 

volumes:
  pg_data:
  grafana-data:

networks:
  jaeger-network:
    driver: bridge
  monitoring:
    driver: bridge
