apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.databaseSecret }}
              key: {{ .Values.db.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.databaseSecret }}
              key: {{ .Values.db.password }}
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.databaseSecret }}
              key: {{ .Values.db.database }}
        ports:
        - containerPort: 5432
