repositories:
  - name: books-api
    url: file://./charts/books-api  # Usa o chart local

helmDefaults:
  wait: true
  timeout: 180
  atomic: true
  createNamespace: true  # Cria o namespace se não existir

releases:
  - name: books-api
    namespace: books
    chart: books-api
    values:
      - values/base.yaml.gotmpl
      - values/base-api.yaml.gotmpl
