image:
  repository: gmonteiro/books-api
  tag: 0.0.1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

replicaCount: 1

db:
  databaseSecret: "postgres-credentials"
  user: "POSTGRES_USER"
  password: "POSTGRES_PASSWORD"
  database: "POSTGRES_DB"
  dbUrl: "DB_URL"